apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: gw2-cluster
  namespace: default
spec:
  bundlesRef:
    apiVersion: anywhere.eks.amazonaws.com/v1alpha1
    name: bundles-21
    namespace: eksa-system
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 1
    endpoint:
      host: 10.4.4.73
    machineGroupRef:
      kind: VSphereMachineConfig
      name: gw2-cluster-cp
  datacenterRef:
    kind: VSphereDatacenterConfig
    name: gw2-cluster-dc
  externalEtcdConfiguration:
    count: 1
    machineGroupRef:
      kind: VSphereMachineConfig
      name: gw2-cluster-etcd
  gitOpsRef:
    kind: FluxConfig
    name: gw2-cluster-gitops
  identityProviderRefs:
  - kind: AWSIamConfig
    name: aws-iam-auth-config
  kubernetesVersion: "1.22"
  managementCluster:
    name: gw2-cluster
  workerNodeGroupConfigurations:
  - count: 1
    machineGroupRef:
      kind: VSphereMachineConfig
      name: gw2-cluster-dp
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereDatacenterConfig
metadata:
  name: gw2-cluster-dc
  namespace: default
spec:
  datacenter: SDDC-Datacenter
  insecure: false
  network: /SDDC-Datacenter/network/eks-workload-network
  server: vcenter.sddc-18-211-251-188.vmwarevmc.com
  thumbprint: A7:07:A6:9D:C4:FA:62:85:80:ED:00:4C:85:F4:38:8A:D0:69:F8:36

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  name: gw2-cluster-dp
  namespace: default
spec:
  datastore: /SDDC-Datacenter/datastore/WorkloadDatastore
  diskGiB: 25
  folder: /SDDC-Datacenter/vm/Spectralink-POC/clusters-dir
  memoryMiB: 8192
  numCPUs: 2
  osFamily: ubuntu
  resourcePool: /SDDC-Datacenter/host/Cluster-1/Resources/Compute-ResourcePool/AMER-LATAM-ResourcePool
  template: /SDDC-Datacenter/vm/Templates/eks-a-templates/ubuntu-v1.22.6-eks-d-1-22-6-eks-a-10-amd64
  users:
  - name: eksa
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDVe/i/Q/IKJWjVtYA2FAl5JwFKdmVsQXWQFYc9eChIOHjtrIbeNEUPo4wQaaDFByq5Zvha30Q5d1WpX18D3qTusYBSzhXePm2lSOjwRUXikNVZ2DP2z6AhhEZwHRHueiWejHYYG0Uze7pg6mKVRbNraOzsBZTNLOQvYj6Uj1dQ3SRg2U45SWn6kdQ04mu7Nl8HCcFgmLdrgK7jHFmdWx260+EYfAENzXJPPQ6C6a2fi/FgvdlSOk0O/mTkMYZVf28f8mH/8dp9SeJzj8Y3b3w5jKC+1x/z34nBdhLIDuYere5EEPnJZjDNh/RrpC8nW8ueqvqmjIwregQ6/XATQPXnF+xUNrEGQMcWy9o0L6RSFUuYW9ydrecg+VE75dxGAMZYFjo/K7Rs3DW3JyWn1WgwAZECzyIvPkUR7WF4pHVUER5SUXSewRE6RhkjLSCxRvLATXSEtLp4opyNVdWYDTFHjbcbcXJU1zIJ/+BmEUlz9z4F5KlknnkvCLMGRBHK/F0/zGzGjwh21Jy7XeQrTvn+uUyHmoGOxqGGD2vd/zXxEvw60xSZrC0/D3U1L5elP+5Zd39Hnsozz7soRQzhoCJ8rHVm2hCLT8rXUKHKgTEm2NJLCeELdcIozImaSfndqF9bEm8QCyUA8AhMI+9RlzpdxK47nudCp35dk+gs9H8tbQ==

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/control-plane: "true"
  name: gw2-cluster-cp
  namespace: default
spec:
  datastore: /SDDC-Datacenter/datastore/WorkloadDatastore
  diskGiB: 25
  folder: /SDDC-Datacenter/vm/Spectralink-POC/clusters-dir
  memoryMiB: 8192
  numCPUs: 2
  osFamily: ubuntu
  resourcePool: /SDDC-Datacenter/host/Cluster-1/Resources/Compute-ResourcePool/AMER-LATAM-ResourcePool
  template: /SDDC-Datacenter/vm/Templates/eks-a-templates/ubuntu-v1.22.6-eks-d-1-22-6-eks-a-10-amd64
  users:
  - name: eksa
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDVe/i/Q/IKJWjVtYA2FAl5JwFKdmVsQXWQFYc9eChIOHjtrIbeNEUPo4wQaaDFByq5Zvha30Q5d1WpX18D3qTusYBSzhXePm2lSOjwRUXikNVZ2DP2z6AhhEZwHRHueiWejHYYG0Uze7pg6mKVRbNraOzsBZTNLOQvYj6Uj1dQ3SRg2U45SWn6kdQ04mu7Nl8HCcFgmLdrgK7jHFmdWx260+EYfAENzXJPPQ6C6a2fi/FgvdlSOk0O/mTkMYZVf28f8mH/8dp9SeJzj8Y3b3w5jKC+1x/z34nBdhLIDuYere5EEPnJZjDNh/RrpC8nW8ueqvqmjIwregQ6/XATQPXnF+xUNrEGQMcWy9o0L6RSFUuYW9ydrecg+VE75dxGAMZYFjo/K7Rs3DW3JyWn1WgwAZECzyIvPkUR7WF4pHVUER5SUXSewRE6RhkjLSCxRvLATXSEtLp4opyNVdWYDTFHjbcbcXJU1zIJ/+BmEUlz9z4F5KlknnkvCLMGRBHK/F0/zGzGjwh21Jy7XeQrTvn+uUyHmoGOxqGGD2vd/zXxEvw60xSZrC0/D3U1L5elP+5Zd39Hnsozz7soRQzhoCJ8rHVm2hCLT8rXUKHKgTEm2NJLCeELdcIozImaSfndqF9bEm8QCyUA8AhMI+9RlzpdxK47nudCp35dk+gs9H8tbQ==

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: VSphereMachineConfig
metadata:
  annotations:
    anywhere.eks.amazonaws.com/etcd: "true"
  name: gw2-cluster-etcd
  namespace: default
spec:
  datastore: /SDDC-Datacenter/datastore/WorkloadDatastore
  diskGiB: 25
  folder: /SDDC-Datacenter/vm/Spectralink-POC/clusters-dir
  memoryMiB: 8192
  numCPUs: 2
  osFamily: ubuntu
  resourcePool: /SDDC-Datacenter/host/Cluster-1/Resources/Compute-ResourcePool/AMER-LATAM-ResourcePool
  template: /SDDC-Datacenter/vm/Templates/eks-a-templates/ubuntu-v1.22.6-eks-d-1-22-6-eks-a-10-amd64
  users:
  - name: eksa
    sshAuthorizedKeys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDVe/i/Q/IKJWjVtYA2FAl5JwFKdmVsQXWQFYc9eChIOHjtrIbeNEUPo4wQaaDFByq5Zvha30Q5d1WpX18D3qTusYBSzhXePm2lSOjwRUXikNVZ2DP2z6AhhEZwHRHueiWejHYYG0Uze7pg6mKVRbNraOzsBZTNLOQvYj6Uj1dQ3SRg2U45SWn6kdQ04mu7Nl8HCcFgmLdrgK7jHFmdWx260+EYfAENzXJPPQ6C6a2fi/FgvdlSOk0O/mTkMYZVf28f8mH/8dp9SeJzj8Y3b3w5jKC+1x/z34nBdhLIDuYere5EEPnJZjDNh/RrpC8nW8ueqvqmjIwregQ6/XATQPXnF+xUNrEGQMcWy9o0L6RSFUuYW9ydrecg+VE75dxGAMZYFjo/K7Rs3DW3JyWn1WgwAZECzyIvPkUR7WF4pHVUER5SUXSewRE6RhkjLSCxRvLATXSEtLp4opyNVdWYDTFHjbcbcXJU1zIJ/+BmEUlz9z4F5KlknnkvCLMGRBHK/F0/zGzGjwh21Jy7XeQrTvn+uUyHmoGOxqGGD2vd/zXxEvw60xSZrC0/D3U1L5elP+5Zd39Hnsozz7soRQzhoCJ8rHVm2hCLT8rXUKHKgTEm2NJLCeELdcIozImaSfndqF9bEm8QCyUA8AhMI+9RlzpdxK47nudCp35dk+gs9H8tbQ==

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
  name: gw2-cluster-gitops
  namespace: default
spec:
  branch: main
  clusterConfigPath: clusters/gw2-cluster
  git:
    repositoryUrl: ssh://git@github.com/prakkie-others/gw2-cluster-gitops.git
    sshKeyAlgorithm: rsa
  systemNamespace: flux-system

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: AWSIamConfig
metadata:
  name: aws-iam-auth-config
  namespace: default
spec:
  awsRegion: us-west-2
  backendMode:
  - EKSConfigMap
  mapRoles:
  - groups:
    - system:masters
    roleARN: arn:aws:iam::505670647613:role/GW2-IRSA-AMP-Role
    username: gw2-cluster-admin
  - groups:
    - system:masters
    roleARN: arn:aws:iam::505670647613:role/GW2-IRSA-AMP-Role
    username: test-sa
  partition: aws

---
